/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import DomainModels.doanhThu;
import ServiceImpl.doanhThuService;
import Services.ThongBao.thongBao;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class doanhThuFrm extends javax.swing.JPanel {

    List<doanhThu> listDoanhThus;
    private doanhThuService dtService;
    DefaultTableModel model;

    public doanhThuFrm() {
        initComponents();
        datePicker1.getSettings().setAllowKeyboardEditing(false);

        listDoanhThus = new ArrayList<>();
        dtService = new doanhThuService();
        model = new DefaultTableModel();

        loadTable();
        tinhTongDT();
    }

    public void loadTable() {
        //listDoanhThus = dtService.find_AllDoanhThu();
        listDoanhThus = dtService.find_AllDoanhThu();
        model = (DefaultTableModel) tbTkeDoanhThu.getModel();
        model.setRowCount(0);
        for (doanhThu dt : listDoanhThus) {
            Object[] row = new Object[4];
            row[0] = dt.getMaHoaDon();
            row[1] = dt.getNgayTao();
            row[2] = dt.getThanhTien();

            model.addRow(row);
        }
    }

    public void tinhTongDT() {
        String number = "###,###,###";
        NumberFormat numberFormat = new DecimalFormat(number);
        int tong = 0;
        int dem = 0;
        for (int i = 0; i < tbTkeDoanhThu.getRowCount(); i++) {
            tong += Integer.parseInt(tbTkeDoanhThu.getValueAt(i, 2).toString());
            dem++;
        }
        lbnTongDoanhThu.setText("Tổng Doanh Thu: " + numberFormat.format(tong) + " VNĐ ");
        lbnTongSoHD.setText("Tổng Số Hóa Đơn: " + numberFormat.format(dem));
    }

    public void shearch() {

        String date = datePicker1.getText().toString();
        if (date == null || date.isEmpty()) {
            thongBao.thongbao("Chưa nhập dữ liệu cần shearch", "");
            return;
        } else if (date.length() > 0) {
            listDoanhThus = dtService.find_Shearch(date);
            model = (DefaultTableModel) tbTkeDoanhThu.getModel();
            model.setRowCount(0);
            for (doanhThu dt : listDoanhThus) {
                Object[] row = new Object[4];
                row[0] = dt.getMaHoaDon();
                row[1] = dt.getNgayTao();
                row[2] = dt.getThanhTien();

                model.addRow(row);
            }
        }
        if (listDoanhThus.isEmpty()) {
            thongBao.thongbao("Shearch Thất Bại", "");
            return;
        } else {
            thongBao.thongbao("Shearch Thành Công", "");
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbTkeDoanhThu = new javax.swing.JTable();
        lbnTongDoanhThu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        btnShearch = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        lbnTongSoHD = new javax.swing.JLabel();

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Tại thời gian");

        jButton6.setText("Refesh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tbTkeDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Ngày tạo", "Thành tiền"
            }
        ));
        jScrollPane4.setViewportView(tbTkeDoanhThu);

        lbnTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbnTongDoanhThu.setText("Tổng Doanh Thu:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thống kê doanh thu");

        btnShearch.setText("Tìm kiếm");
        btnShearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShearchActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lbnTongSoHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbnTongSoHD.setText("Tổng Số Hóa Đơn:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lbnTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(lbnTongSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)))
                        .addGap(654, 654, 654))))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnShearch)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShearch)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbnTongSoHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(lbnTongDoanhThu)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        datePicker1.setText("");
        loadTable();
        tinhTongDT();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnShearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShearchActionPerformed
        shearch();
        tinhTongDT();
    }//GEN-LAST:event_btnShearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShearch;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbnTongDoanhThu;
    private javax.swing.JLabel lbnTongSoHD;
    private javax.swing.JTable tbTkeDoanhThu;
    // End of variables declaration//GEN-END:variables
}
